### ISSUE TITLE
Unfair comparision for triplets and septuplets

### ISSUE THREAD

**Issue by kinoud** [AIVFI/Video-Frame-Interpolation-Rankings-and-Video-Deblurring-Rankings#1]
In my understanding, Vimeo90K dataset is comprised of 2 splits: triplets and septuplets. Triplets split aims for task of interpolating 1 frame out of 2 neighbor frames. Septuplets split aims for task of interpolating 1 frame out of 4 neighbor frames. Both splits have their own training/evaluation set. In order to fairly compare models, you should evaluate them on the same split, i.e. triplets split or septuplets split. But your table seems to have mixed results from both splits.

**Comment by AIVFI** [comment]
You are absolutely right. The split is done.
